name: deploy-pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install MkDocs and Material theme
        run: pip install mkdocs-material
      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
